learning_users/basic_app/urls.py
from django.conf.urls import url
from basic_app import views

#template urls!

app_name = 'basic_app'

urlpatterns = [
    url(r'^register/$',views.register,name="register"),
    url(r'^login/$',views.user_login,name="login"),

]

learning_users/learning_users/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from basic_app import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$',views.index,name='index'),
    url(r'^basic_app/',include('basic_app.urls')),
    url(r'^logout/$',views.user_logout,name='logout'),
    url(r'^special/$',views.special,name='special'),


]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

learning_users/basic_app/models.py
from django.db import models
#connect to USER database from admin
from django.contrib.auth.models import User
# Create your models here.

#extend the user module coming with Django
class UserProfileInfo(models.Model):

    #create relationship (don't inherit from User! just one2one mapping)
    user = models.OneToOneField(User,on_delete=models.CASCADE)

    # Add any additional attributes you want
    #we add url to portfolio of user and picture
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

    #decide of what should be shown in the admin model, we choose username
    def __str__(self):
        #built-in attribute of django.contrib.auth.models.User !
        return self.user.username

learning_users/basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model=User
        fields = ('username','email','password')

class UserProfileInfoForm(forms.ModelForm):

    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

learning_users/basic_app/views.py
from django.shortcuts import render
from basic_app.forms import UserForm,UserProfileInfoForm

#for login
from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required







# Create your views here.
def index(request):
    return render (request,'basic_app/index.html')

#you need this decorator to only apply it to logged in users
@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

@login_required
def special(request):
    return HttpResponse('you are logged in')



def register(request):

    registered = False

    if request.method == "POST":

        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request,'basic_app/registration.html',
                            {'user_form':user_form,
                            'profile_form':profile_form,
                            'registered':registered})


#login-dont call the view login, logout!

def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        #this authenticates
        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("ACCOUNT IS NOT ACTIVE")

        else:
            print("someone tried to login and failed")
            print("username:{} and password {}".format(username,password))
            return HttpResponse("invalid login details supplied")
    else:
        return render (request,'basic_app/login.html',{})

learning_users/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>

    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{%url 'index'%}">DJANGO</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">

          <li class="nav-item"><a class="nav-link" href="{%url 'admin:index'%}">Admin</a> </li>
          <li class="nav-item"><a class="nav-link" href="{%url 'basic_app:register'%}">Register</a> </li>

          {% if user.is_authenticated%}

          <li class="nav-item"><a class="nav-link" href="{%url 'logout'%}">Logout</a>  </li>
          <li class="nav-item"><a class="nav-link" href="{%url 'special'%}">Special</a>  </li>
          {%else%}
          <li class="nav-item"><a class="nav-link" href="{%url 'basic_app:login'%}">Login</a>  </li>

          {%endif %}


        </ul>
      </div>
    </nav>
    <div class="container">
      {% block body_block %}
      {% endblock %}
    </div>


  </body>
</html>

learning_users/templates/basic_app/index.html
{%extends 'basic_app/base.html'%}

{%block body_block%}

<div class="jumbotron">
  <h1>Django Level Five Index</h1>

</div>

{%endblock%}

learning_users/templates/basic_app/login.html
{%extends 'basic_app/base.html'%}
{%block body_block %}

<div class="jumbotron">
  <h1>Please login</h1>
  <form action="{%url 'basic_app:login'%}" method="post">
    {% csrf_token %}
    <label for="username">Username:</label>
    <input type="text" name="username" value="enter username">

    <label for="password">Password:</label>
    <input type="password" name="password" value="">

    <input type="submit" name="" value="login">
  </form>

</div>
{%endblock%}

learning_users/templates/basic_app/registration.html
{%extends 'basic_app/base.html'%}

{% load staticfiles%}

{% block body_block%}

<div class="jumbotron">
  {%if registered%}
  <h1>Thank you for registring!</h1>
  {%else%}
  <h1>Register Here</h1>
  <h3>FIll out the form:</h3>
  ##use type multipart as you upload pictures plus text
  <form enctype="multipart/form-data" method="post" >

    #security
    {%csrf_token%}
    #defined in view
    {{user_form.as_p}}
    {{profile_form.as_p}}
    <input type="submit" name="" value="Register">

  </form>


  {%endif%}


</div>

{%endblock%}